### ISSUE TITLE
Second starting on Widnows 8.1 cause Exception

### ISSUE THREAD

**Issue by vit1251** [UprootLabs/gngr#82] opened 2015-01-15 14:22 UTC
??? 15, 2015 6:21:51 PM org.lobobrowser.main.ReuseManager launch
WARNING: Another instance of the application must have been running but was not shut down properly.
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at org.lobobrowser.main.ReuseManager.launch(ReuseManager.java:94)
        at org.lobobrowser.main.EntryPoint.launch(EntryPoint.java:63)
        at org.lobobrowser.main.EntryPoint.lambda$0(EntryPoint.java:79)
        at org.lobobrowser.main.EntryPoint$$Lambda$1/2061475679.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lobobrowser.main.EntryPoint.privilegedLaunch(EntryPoint.java:78)
        at org.lobobrowser.main.EntryPoint.main(EntryPoint.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at uno.Uno$3.run(Uno.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at uno.Uno.startMain(Uno.java:193)
        at uno.Uno.main(Uno.java:233)

**Comment by hrj** [comment] 2015-01-15 14:28
Are you getting this warning while a `gngr` window is still open? If so, then it is a feature not a bug. This feature prevents a new process from being created if `gngr` is already running, similar to other browsers. We just need to remove the exception and give a nice message.

If you are getting a warning when all `gngr` windows are closed, then it is a bug.

**Comment by hrj** [comment] 2015-01-15 14:29
Ignore previous comment, I read the exception incorrectly.

**Comment by hrj** [comment] 2015-01-15 14:50
I tried multiple starts on Windows 7 and didn't see any problems.

The warning and exception is shown only if the previous instance of `gngr` was not shutdown correctly. Did you close `gngr` by killing the process instead of closing the window?

Note that the warning and exception are only for information. Functionality should not be affected. I will remove the scary stack trace in next release.

**Closed** 2015-01-15 18:57 UTC
